apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This field tells Kustomize to apply these comman labels
labels:
- includeSelectors: true
  pairs:
    env: dev
    
#Reference to base folder
resources:
- ../../../base/namespaces

# This field tells Kustomize to apply this namespace to all resources
namespace: dev

